AWSTemplateFormatVersion: 2010-09-09
Description: "Secure CI/CD Pipeline for Containerized Applications Using GitHub Actions and Amazon ECR"

Resources:
  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: GitHub Actions OIDC 

  GitHubActionsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GitHubActionsServiceRole
            Effect: Allow
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:alfreddey/aws-ecr:ref:refs/heads/main"
      Description: Role for GitHub Actions to assume
      Policies:
        - PolicyName: ECRPushPullPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowECRAuth
                Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Sid: AllowECRPushPull
                Effect: Allow
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:PutImage"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:CompleteLayerUpload"
                Resource: !GetAtt ECRRepository.Arn

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "alfreddey_guess_game"